### ISSUE TITLE
Farmer stops on insatall

### ISSUE THREAD

**Issue by Lowestofttim** [Pipscoin-Network/pipscoin-blockchain#14]
Windows 10

On Initial load all .exe files start wallet, full node, harvester and farmer. But the farmer then imediatly shuts itself down.

When run in cli i get this error

Daemon not started yet
Starting daemon
pipscoin_harvester: started
pipscoin_farmer: started
pipscoin_full_node: started
pipscoin_wallet: started
PS C:\Users\t_you\AppData\Local\pipscoin-blockchain\app-1.0.0\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "pipscoin\server\start_farmer.py", line 68, in <module>
  File "pipscoin\server\start_farmer.py", line 63, in main
  File "pipscoin\server\start_farmer.py", line 38, in service_kwargs_for_farmer
  File "pipscoin\farmer\farmer.py", line 120, in __init__
RuntimeError: No keys exist. Please run 'pipscoin keys generate' or open the UI.
[33396] Failed to execute script start_farmer
Traceback (most recent call last):
  File "pipscoin\server\start_full_node.py", line 65, in <module>
  File "pipscoin\server\start_full_node.py", line 60, in main
Exception in thread Thread-3:
Traceback (most recent call last):
  File "aiosqlite\core.py", line 109, in run
  File "asyncio\base_events.py", line 736, in call_soon_threadsafe
  File "asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "aiosqlite\core.py", line 117, in run
  File "asyncio\base_events.py", line 736, in call_soon_threadsafe
  File "asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed
  File "pipscoin\server\start_service.py", line 255, in run_service

  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "pipscoin\server\start_service.py", line 249, in async_run_service
  File "pipscoin\server\start_service.py", line 171, in run
  File "pipscoin\server\start_service.py", line 143, in start
  File "pipscoin\server\server.py", line 215, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8888): only one usage of each socket address (protocol/network address/port) is normally permitted
[39824] Failed to execute script start_full_node

**Comment by Lowestofttim** [comment]
Tried shutting down all other forks and still no joy

Tried deleting all pips folders and fresh install, same issue.

**Comment by Pipscoin-Network** [comment]
Thank you for sharing the information - We will look into. Currently we have a fair amount of users on the Windows install and will check with the user base if they are experiencing the issue. :)

**Comment by Pipscoin-Network** [comment]
Found the issue - conflict with 3rd party software corepool client on port 8888. We will be taking next steps with this issue shortly to resolve for other users.
