### ISSUE TITLE
Cannot connect with dns introducer on por 7477

### ISSUE THREAD

**Issue by Zelza-Sagaz** [Pipscoin-Network/pipscoin-blockchain#16]
2021-09-02T18:23:14.748 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 7477}
2021-09-02T18:23:15.786 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 7477}
2021-09-02T18:23:16.335 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:23:16.336 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:23:16.337 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:23:24.399 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:23:24.400 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:23:24.401 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:23:26.462 full_node full_node_server        : INFO     Cannot connect to host pipscoin:443 ssl:<ssl.SSLContext object at 0x000001A49D82C7B8> [getaddrinfo failed]
2021-09-02T18:23:26.463 full_node pipscoin.rpc.rpc_server : WARNING  Error while handling message: Traceback (most recent call last):
  File "pipscoin\rpc\rpc_server.py", line 212, in safe_handle
  File "pipscoin\rpc\rpc_server.py", line 200, in ws_api
  File "pipscoin\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-09-02T18:23:31.887 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:23:34.914 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:23:34.915 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:23:34.916 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:23:42.998 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:23:42.999 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:23:42.999 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:23:50.493 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:23:53.530 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:23:53.531 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:23:53.532 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:23:58.802 full_node full_node_server        : INFO     Cannot connect to host pipscoin:443 ssl:<ssl.SSLContext object at 0x000001A49D7B5F98> [getaddrinfo failed]
2021-09-02T18:23:58.803 full_node pipscoin.rpc.rpc_server : WARNING  Error while handling message: Traceback (most recent call last):
  File "pipscoin\rpc\rpc_server.py", line 212, in safe_handle
  File "pipscoin\rpc\rpc_server.py", line 200, in ws_api
  File "pipscoin\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-09-02T18:24:01.705 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:01.706 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:01.707 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:24:09.199 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:24:12.720 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:12.721 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:12.722 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:24:13.198 wallet pipscoin.wallet.wallet_node: INFO     Will not attempt to connect to other nodes, already connected to {'host': 'localhost', 'port': 7477}
2021-09-02T18:24:20.837 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:20.838 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:20.839 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:24:28.337 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:24:31.549 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:31.551 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:31.551 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:24:39.597 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:39.599 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:39.599 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:24:42.093 full_node full_node_server        : INFO     Cannot connect to host pipscoin:443 ssl:<ssl.SSLContext object at 0x000001A49D82C7B8> [getaddrinfo failed]
2021-09-02T18:24:42.094 full_node pipscoin.rpc.rpc_server : WARNING  Error while handling message: Traceback (most recent call last):
  File "pipscoin\rpc\rpc_server.py", line 212, in safe_handle
  File "pipscoin\rpc\rpc_server.py", line 200, in ws_api
  File "pipscoin\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-09-02T18:24:47.083 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:24:50.144 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:50.145 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:50.146 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:24:58.210 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:24:58.211 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:24:58.212 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:25:05.709 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:25:08.735 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:25:08.736 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:25:08.737 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:25:16.808 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:25:16.810 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:25:16.810 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:25:24.309 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:25:27.368 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:25:27.369 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:25:27.370 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:25:35.510 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:25:35.511 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:25:35.512 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:25:42.993 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:25:46.115 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:25:46.116 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:25:46.116 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:25:54.191 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:25:54.192 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:25:54.193 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}
2021-09-02T18:26:01.692 full_node pipscoin.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-09-02T18:26:05.302 full_node full_node_server        : INFO     Connected with full_node {'host': 'introducer.pipscoin.net', 'port': 7477}
2021-09-02T18:26:05.304 full_node full_node_server        : INFO     Connection closed: introducer.pipscoin.net, node id: f19c626e8fb5efd6e46f38d5aa66803e3be4116cdc5b8318b75ce7e31dbec20d
2021-09-02T18:26:05.304 full_node pipscoin.full_node.full_node: INFO     peer disconnected {'host': '104.194.9.25', 'port': 7477}

**Comment by faikuluturk** [comment]
delete .pipscoin folder and  resynch  from zero
